#!/usr/bin/env python3
"""Convert one official LROC NAC DTM crop into a compact C++ height table.

The checked-in table is deliberately small enough to ship with the prototype.
It is a 129 x 129 resample of a 1024 m square from NAC_DTM_NOBILE03, an
official 4 m/px DTM covering terrain near Nobile crater and Mons Mouton.

Dependencies: numpy, tifffile
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import tifffile


SOURCE_URL = (
    "https://pds.lroc.im-ldi.com/data/LRO-L-LROC-5-RDR-V1.0/"
    "LROLRC_2001/DATA/SDP/NAC_DTM/NOBILE03/NAC_DTM_NOBILE03.TIF"
)
SOURCE_ID = "NAC_DTM_NOBILE03"
CROP_X = 384
CROP_Y = 448
CROP_SIZE = 256
OUTPUT_SIZE = 129


def resample_bilinear(source: np.ndarray, size: int) -> np.ndarray:
    source_y = np.linspace(0.0, source.shape[0] - 1.0, size)
    source_x = np.linspace(0.0, source.shape[1] - 1.0, size)
    x0 = np.floor(source_x).astype(np.int32)
    y0 = np.floor(source_y).astype(np.int32)
    x1 = np.minimum(x0 + 1, source.shape[1] - 1)
    y1 = np.minimum(y0 + 1, source.shape[0] - 1)
    tx = source_x - x0
    ty = source_y - y0
    top = source[np.ix_(y0, x0)] * (1.0 - tx) + source[np.ix_(y0, x1)] * tx
    bottom = source[np.ix_(y1, x0)] * (1.0 - tx) + source[np.ix_(y1, x1)] * tx
    return top * (1.0 - ty[:, None]) + bottom * ty[:, None]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source_tif", type=Path)
    parser.add_argument("output_inl", type=Path)
    args = parser.parse_args()

    image = tifffile.imread(args.source_tif).astype(np.float64)
    crop = image[CROP_Y : CROP_Y + CROP_SIZE, CROP_X : CROP_X + CROP_SIZE]
    if crop.shape != (CROP_SIZE, CROP_SIZE):
        raise SystemExit(f"unexpected crop shape: {crop.shape}")
    if not np.all(np.isfinite(crop) & (crop > -1.0e20)):
        raise SystemExit("selected crop contains invalid DTM samples")

    sampled = resample_bilinear(crop, OUTPUT_SIZE)
    minimum = float(sampled.min())
    maximum = float(sampled.max())
    quantized = np.rint((sampled - minimum) * 65535.0 / (maximum - minimum)).astype(np.uint16)

    values = quantized.reshape(-1)
    rows = []
    for index in range(0, values.size, 16):
        rows.append("    " + ", ".join(str(int(value)) for value in values[index : index + 16]) + ",")

    text = f"""// Generated by Tools/PrepareLunarTerrain.py. Do not hand edit.
// Source: {SOURCE_ID}
// URL: {SOURCE_URL}
// Source scale: 4 m/px. Crop: x={CROP_X}, y={CROP_Y}, {CROP_SIZE} x {CROP_SIZE} px.
// The 1024 m square is bilinearly resampled to {OUTPUT_SIZE} x {OUTPUT_SIZE} and quantized to uint16.
inline constexpr int32 Nobile03HeightResolution = {OUTPUT_SIZE};
inline constexpr float Nobile03GroundSizeMeters = 1024.0f;
inline constexpr float Nobile03MinimumElevationMeters = {minimum:.9f}f;
inline constexpr float Nobile03MaximumElevationMeters = {maximum:.9f}f;
inline constexpr uint16 Nobile03HeightSamples[{values.size}] =
{{
{chr(10).join(rows)}
}};
"""
    args.output_inl.parent.mkdir(parents=True, exist_ok=True)
    args.output_inl.write_text(text, encoding="utf-8", newline="\n")
    print(
        f"wrote {args.output_inl}: {OUTPUT_SIZE}x{OUTPUT_SIZE}, "
        f"elevation {minimum:.3f}..{maximum:.3f} m"
    )


if __name__ == "__main__":
    main()
